version: '3.8'

networks:
  test:
    driver: bridge

services:
  test-database:
    image: postgres:15-alpine
    container_name: test-deck-hunter-db
    hostname: test-deck-hunter-db
    ports:
      - 5632:${DB_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    restart: unless-stopped
    networks:
      - ${NODE_ENV}
    tty: true

  test-backend:
    extends:
      file: ./docker-compose.dev.yml
      service: backend
    container_name: test-deck-hunter-be
    ports:
      - ${APP_PORT:-3200}:3000
    networks:
      - ${NODE_ENV}
