version: '3.8'

networks:
  development:
    driver: bridge

services:
  ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama:latest
    ports:
      - ${DH_OLLAMA_PORT:-11434}:11434
    environment:
      OLLAMA_PORT: ${DH_OLLAMA_PORT}
    restart: unless-stopped

  database:
    image: postgres:15-alpine
    container_name: deck-hunter-db
    hostname: deck-hunter-db
    ports:
      - 5432:${DH_DB_PORT}
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DH_DB_USER}
      POSTGRES_PASSWORD: ${DH_DB_PASS}
      POSTGRES_DB: ${DH_DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    restart: unless-stopped
    networks:
      - ${DH_NODE_ENV}
    tty: true

  backend:
    container_name: deck-hunter-be
    hostname: deck-hunter-be
    build:
      context: .
      target: ${DH_NODE_ENV}
    ports:
      - ${DH_APP_PORT:-3000}:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./node_modules:/usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json:ro
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json:ro
      - ./tsconfig.json:/usr/src/app/tsconfig.json:ro
    environment:
      DH_NODE_ENV: ${DH_NODE_ENV}
      APP_PORT: ${DH_APP_PORT}
    restart: unless-stopped
    networks:
      - ${DH_NODE_ENV}
    tty: true
